spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnpayment
    username: root
    password: Karthik@123
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.globally_quoted_identifiers: true

